# Default values for servpod.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
nameOverride: ""
fullnameOverride: ""

image:
  repository: dmytrothr/calc_server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 9999

resources:
  requests:
    cpu: 200m
    memory: '200Mi'
  limits:
    cpu: 500m
    memory: '500Mi'