apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
          resources:
            {{- if .Values.resources.requests.cpu }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
            {{- end }}
            {{- if .Values.resources.requests.memory }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
            {{- end }}
            {{- if .Values.resources.limits.cpu }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.resources.limits.memory }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
            {{- end }}    