apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: calc-hpa
spec:
    minReplicas: 1
    maxReplicas: 3
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: {{ include "application.fullname" . }}
    targetCPUUtilizationPercentage: 50