# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 30333, host: 30333
  config.vm.network "private_network", ip: "192.168.56.111"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 4000 
     vb.cpus = 2
  end

  config.vm.provision :shell, path: "minikube.sh"
end
