# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

 #config.vm.network "forwarded_port", guest: 8888, host: 8080
  config.vm.network "private_network", ip: "192.168.56.222"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048 
     vb.cpus = 2
  end

  config.vm.provision :shell, path: "cipipe.sh"
end
