def clientPath = "cd/helm/client"
def serverPath = "cd/helm/server"

pipeline{
    agent any

    environment {
        version = readFile 'version.txt'
    }

    stages{
        stage('Helm linter'){
            steps{
                sh "helm lint ${clientPath}"
                sh "helm lint ${serverPath}"
            }
        }

        stage('Helm install'){
            steps{
                sh "helm install ${clientPath} --name calc-client --set image.tag=$version"
                sh "helm install ${serverPath} --name calc-server --set image.tag=$version"
            }
        }
    }
}