def version = "1.0.${env.BUILD_NUMBER}"
def clientPath = "cd/helm/client"
def serverPath = "cd/helm/server"

pipeline{
    agent any

    stages{
        stage('Helm linter'){
            steps{
                sh "helm lint ${clientPath}"
                sh "helm lint ${serverPath}"
            }
        }
    }
}