pipeline{
    agent any

    stages{
        stage('Build docker image'){
            steps{
                sh 'make docker-build'
            }
        }
        stage('Push docker image'){
            steps{
                sh "cat version.txt > version"
                withCredentials([usernamePassword(credentialsId: 'dockersecret', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh "docker login -u ${USERNAME} -p ${PASSWORD}"
                }
                sh "version=`cat version.txt`"
                sh "docker tag calc_client dmytrothr/calc_client:${version}"
                sh "docker tag calc_server dmytrothr/calc_server:${version}"
                sh "docker push dmytrothr/calc_client:${version}"
                sh "docker push dmytrothr/calc_server:${version}"
            }
        }
    }
}